---
title: "NH증권 직무인터뷰를 읽고<br>(트레이딩&빅데이터)"
author: "Kibok Park"
date: "2024-04-28"
categories: [직무분석] 
# 경제/금융공부
toc: true

draft: true

comments: 
    giscus:
      repo: kr9268/giscus_for_blog
---

## 참고한 공고 &인터뷰 자료
관심이 생겨서 관련 공고 등을 보고 있는데, 직무이해 겸 모르는 단어를 정리해봅니다.

::: {.callout collapse="true"}
# 참고한 공고 (클릭해서 펼치기)
[NH투자증권 채용공고-Trading](https://nhqv-recruit2024.com/NH1.html)

[NH투자증권 채용공고-빅데이터 분석](https://nhqv-recruit2024.com/interview_u_08.html)

[NH투자증권 직무인터뷰](https://nhqv-recruit2024.com/interview_u_04.html)
::: 

## 트레이딩 직무 단어정리
* 프랍 트레이딩(Proprietary Trading) : 고객이 아닌 금융회사의 돈으로 주식이나 파생상품 등 금융상품을 거래하는 것
                                     (=자기계정거래, 자기계좌거래, 고유계정거래, 고유계좌거래)

 >**`프랍트레이딩`**은 통상 선물·옵션 등 `파생상품 부문`, 일반적 주식투자 같은 `방향성 매매`, 알고리즘에 따라 투자하는  `시스템 매매`, `채권투자`, 부동산이나 인프라 등의 `대체투자` 등으로 나뉜다. 보통 [자기매매 비중이 높은 중소형 증권사]{.underline}에는 많게는 50여명에 이르는 프랍트레이더들이 있다. 이 가운데 [80% 이상이 파생 트레이더다.]{.underline}<br>[중소형 증권사들의 파생상품투자 비중이 높은 것은 비용이 싸기 때문이다.]{.underline} 증권사의 경우 선물·옵션 거래시 `사후 증거금 제도`가 적용된다. 장중 거래에는 증거금이 따로 필요 없고 장 마감 후 포지션 규모에 따라 증거금을 마련하면 된다. 따라서 [장중에는 활발히 거래하고 장 마감 직전 파생상품을 보유하지 않았으면 증거금 부담은 없다.]{.underline} [하루 단위로 청산하는 경우 사실상 금융비용은 없다.]{.underline}
>
> [상기내용 참고한 서울경제 기사링크](https://www.sedaily.com/NewsView/1HLP1AH6UG)<br>
> [거래증거금vs위탁증거금 내용 참고할 수 있는 블로그](https://blog.naver.com/vvvtg/223231778959)

* 장내거래 vs 장외거래 : 정규시장 외 체결되는 거래
* 매크로 지식 : Macro economics지식 (↔ Micro economics)
* 서킷브레이커(일시매매정지, Trading Curb) : 가격 변동이 지나친 경우 일시적으로 거래를 중단하는 것
* 틱 : 체결량에 따른 단위 (5틱 = 체결 5회 기준)

* 셀사이드(Sell-side|은행, 증권사 등) : 금융 서비스 등을 제공하여 수익 창출
* 바이사이드(Buy-side|자산운용사, 연기금, 보험사, 헤지펀드 등) : 투자를 하여 수익 창출

>[참고글:셀사이드와 바이사이드의 금융공학](https://brunch.co.kr/@quantdaddy/34)

* 하우스 : 증권사, 금융사 등 단체를 칭함

## 빅데이터 직무 단어정리
* MTS : Mobile Trading System (HTS : Home Trading System)
* 원장 : 증권사가 고객계좌나 거래내역, 매매 등을 관리하는 프로그램